dest = "$HOME"
src = "/dotfiles"

[[modules]]
  src = "$HOME/dev/dotfiles/config/i3"
  target = "i3test"
  # name = "i3testname"

[[modules]]
  src = "nvim"
  dest = "$HOME"
  name = "neovim"

[[groups]]
  src = "config"
  dest = ".config"
  
  [[groups.modules]]
    src = "$HOME/dev/dotfiles/config/alacritty"
    name = "Alacritty"

  [[groups.groups]]
    src = "nested"
    dest = "/root"

    [[groups.groups.modules]]
      src = "here"
      dest = "woo"
      target = "target"

    [[groups.groups.modules]]
      src = "here"
      dest = "/overriderootwoo"
      target = "target"
